name: Auto Push & K8s Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/env-secret.yaml
          kubectl apply -f k8s/agent-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/ingress.yaml